const INTERNAL_SERVER_ERROR = 'Internal server error'
const FORBIDDEN_ERROR = 'Forbidden'
const UNAUTHORIZED_ERROR = 'Unauthorized'

export { INTERNAL_SERVER_ERROR, FORBIDDEN_ERROR, UNAUTHORIZED_ERROR }
